- id: '1716506933201'
  alias: Downstairs Chili Pepper Lights Gate
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.downstairs_bathroom_chili_pepper_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - light.downstairs_bathroom_light
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.downstairs_bathroom_light
    state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.downstairs_bathroom_chili_pepper_lights
  mode: single
- id: nighttime_daytime_mutex
  alias: Nighttime and Daytime Mutex
  description: Ensure Nighttime and Daytime don't overlap
  trigger:
  - platform: state
    entity_id: input_boolean.nighttime
    to: 'on'
  - platform: state
    entity_id: input_boolean.daytime
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.nighttime
        state: 'on'
        for: 00:00:01
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.daytime
    - conditions:
      - condition: state
        entity_id: input_boolean.daytime
        state: 'on'
        for: 00:00:01
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.nighttime
  mode: single
- id: hey_lamp_on
  alias: Hey Lamp On
  description: Flashes the Hey Lamp when toggled on to ensure it's in the right warm
    color state
  triggers:
  - entity_id:
    - light.hey_lamp
    to: 'on'
    trigger: state
    from: 'off'
  conditions: []
  actions:
  - sequence:
    - target:
        entity_id: light.hey_lamp
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 500
    - target:
        entity_id: light.hey_lamp
      action: light.turn_off
      data: {}
    - delay:
        milliseconds: 500
    - target:
        entity_id: light.hey_lamp
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 500
  mode: single
  max_exceeded: silent
- id: hey_lamp_on_2
  alias: Hey Lamp On 2
  description: Flashes the Hey Lamp when toggled on to ensure it's in the right warm
    color state
  triggers:
  - entity_id:
    - light.hey_lamp_2_2
    to: 'on'
    trigger: state
    from: 'off'
  conditions: []
  actions:
  - sequence:
    - target:
        entity_id: light.hey_lamp_2_2
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 500
    - target:
        entity_id: light.hey_lamp_2_2
      action: light.turn_off
      data: {}
    - delay:
        milliseconds: 500
    - target:
        entity_id: light.hey_lamp_2_2
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 500
  mode: single
  max_exceeded: silent