- id: downstairs_bathroom_chili_pepper_lights_gate
  alias: Downstairs Chili Pepper Lights Gate
  description: 'Turns off the downstairs bathroom chili pepper lights when the main light is turned on'
  trigger:
  - platform: state
    entity_id:
    - light.downstairs_bathroom_chili_pepper_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - light.downstairs_bathroom_light
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.downstairs_bathroom_light
    state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.downstairs_bathroom_chili_pepper_lights
  mode: single
- id: guest_bathroom_peppa_pig_lights_gate
  alias: Guest Bathroom Peppa Pig Lights Gate
  description: 'Turns off the guest bathroom Peppa Pig lights when the main light is turned on'
  trigger:
  - platform: state
    entity_id:
    - light.guest_bathroom_peppa_pig_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - light.guest_bathroom_light
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.guest_bathroom_light
    state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.guest_bathroom_peppa_pig_lights
  mode: single
- id: master_bathroom_chili_pepper_lights_gate
  alias: Master Bathroom Chili Pepper Lights Gate
  description: 'Turns off the master bathroom chili pepper lights when either of the main lights are turned on'
  trigger:
  - platform: state
    entity_id:
    - light.master_bathroom_chili_pepper_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - light.master_bathroom_light_1
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - light.master_bathroom_light_2
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: light.master_bathroom_light_1
        state: 'on'
      - condition: state
        entity_id: light.master_bathroom_light_2
        state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.master_bathroom_chili_pepper_lights
  mode: single
- id: hey_lamp_on
  alias: Hey Lamp On
  description: Flashes the Hey Lamp when toggled on to ensure it's in the right warm
    color state
  triggers:
  - entity_id:
    - light.hey_lamp
    to: 'on'
    trigger: state
    from: 'off'
  conditions: []
  actions:
  - sequence:
    - target:
        entity_id: light.hey_lamp
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 200
    - target:
        entity_id: light.hey_lamp
      action: light.turn_off
      data: {}
    - delay:
        milliseconds: 200
    - target:
        entity_id: light.hey_lamp
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 200
  mode: single
  max_exceeded: silent
- id: hey_lamp_on_2
  alias: Hey Lamp On 2
  description: Flashes the Hey Lamp when toggled on to ensure it's in the right warm
    color state
  triggers:
  - entity_id:
    - light.dining_room_christmas_lights
    to: 'on'
    trigger: state
    from: 'off'
  conditions: []
  actions:
  - sequence:
    - target:
        entity_id: light.dining_room_christmas_lights
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 200
    - target:
        entity_id: light.dining_room_christmas_lights
      action: light.turn_off
      data: {}
    - delay:
        milliseconds: 200
    - target:
        entity_id: light.dining_room_christmas_lights
      action: light.turn_on
      data: {}
    - delay:
        milliseconds: 200
  mode: single
  max_exceeded: silent