# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
    - platform: google_translate

group: !include_dir_merge_list group

automation: !include_dir_merge_list automation
scene: !include scenes.yaml
light: !include_dir_merge_list light

input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

zone: !include zone.yaml

template: !include template_sensors.yaml

frontend:
    themes: !include_dir_merge_named themes
