- platform: template
  fans:
      guest_bedroom_dyson_fan:
          friendly_name: "Guest Bedroom Dyson Fan"
          unique_id: "guest_bedroom_dyson_fan"
          value_template:
              "{{ (states('input_text.guest_bedroom_dyson_fan_state') | from_json).state
              == 'on' }}"
          percentage_template:
              "{{ (((states('input_text.guest_bedroom_dyson_fan_state') |
              from_json).speed | float) * 100) | int }}"
          preset_mode_template:
              "{{ (states('input_text.guest_bedroom_dyson_fan_state') |
              from_json).preset_mode }}"
          oscillating_template:
              "{{ (states('input_text.guest_bedroom_dyson_fan_state') |
              from_json).oscillating }}"
          turn_on:
              service: rest_command.remote_fan_command
              data_template:
                  domain: "fan"
                  service: "turn_on"
                  controller_id: "remote.guest_bedroom_rm4_mini"
                  device: "guest_bedroom_dyson_fan"
                  entity_id: "fan.guest_bedroom_dyson_fan"
                  state: "on"
                  percentage: "100"
          turn_off:
              service: rest_command.remote_fan_command
              data_template:
                  domain: "fan"
                  service: "turn_off"
                  controller_id: "remote.guest_bedroom_rm4_mini"
                  device: "guest_bedroom_dyson_fan"
                  entity_id: "fan.guest_bedroom_dyson_fan"
                  state: "off"
                  percentage: "0"

          set_percentage:
              service: rest_command.remote_fan_command
              data_template:
                  domain: "fan"
                  service: "turn_on"
                  controller_id: "remote.guest_bedroom_rm4_mini"
                  device: "guest_bedroom_dyson_fan"
                  entity_id: "fan.guest_bedroom_dyson_fan"
                  state: "on"
                  percentage: "{{ percentage }}"

          set_oscillating:
              service: rest_command.remote_fan_command
              data_template:
                  domain: "fan"
                  service: "oscillate"
                  controller_id: "remote.guest_bedroom_rm4_mini"
                  device: "guest_bedroom_dyson_fan"
                  entity_id: "fan.guest_bedroom_dyson_fan"
                  oscillating: "{{ oscillating | bool }}"
          speed_count: 10
