# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# This gets added to the x,y,z to derive a gps location
gps:
  latitude: 38.897957
  longitude: -77.036560
  elevation: 146

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

optimization:
  enabled: true
  interval_secs: 3600
  limits:
    absorption_min: 2.5
    absorption_max: 3.5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -50
    rx_adj_rssi_min: -15
    rx_adj_rssi_max: 20

weighting:
  algorithm: gaussian
  props:
    sigma: 0.10

# Floors w/ the points to draw it in meters
floors:
  - id: first
    name: First Floor
    # Bounds (x,y,z) of map in meters
    bounds: [[0, 0, 0], [17, 18, 1.5]]
    rooms:
      - name: Powder
        points:
          - [6, 12]
          - [8.6, 12]
          - [8.6, 10]
          - [8, 9]
          - [6, 9]
          - [6, 12]
      - name: Den
        points:
          - [6, 16.2]
          - [9.6, 16.2]
          - [9.6, 13.5]
          - [8.6, 12]
          - [6, 12]
          - [6, 14.5]
      - name: Family
        points:
          - [0, 0.5]
          - [0, 5.5]
          - [5, 5.5]
          - [6, 4.5]
          - [6, 0.5]
          - [5.5, 0]
          - [0.5, 0]
          - [0, 0.5]
      - name: Kitchen
        points:
          - [6, 2]
          - [6, 9]
          - [8, 9]
          - [8.6, 10]
          - [12.5, 10]
          - [12.5, 2]
          - [6, 2]
      - name: Garage
        points:
          - [0, 17]
          - [1.5, 17]
          - [1.5, 17.5]
          - [6, 17.5]
          - [6, 7.5]
          - [0, 7.5]
          - [0, 17]
      - name: Living
        points:
          - [16.5, 13.25]
          - [16.5, 7.75]
          - [12.5, 7.75]
          - [12.5, 13.25]
          - [16.5, 13.25]
      - name: Dining
        points:
          - [16.5, 2.75]
          - [16.5, 7.75]
          - [12.5, 7.75]
          - [12.5, 2.75]
          - [16.5, 2.75]
      - name: Foyer
        points:
          - [9.6, 13.5]
          - [9.6, 15]
          - [12.5, 15]
          - [12.5, 10]
          - [11.6, 10]
          - [8.6, 10]
          - [8.6, 12]
      - name: Laundry
        points:
          - [0, 7.5]
          - [3.6, 7.5]
          - [3.6, 5.5]
          - [0, 5.5]
          - [0, 7.5]
  - id: second
    name: Second Floor
    bounds: [[0, 0, 3.1], [17, 18, 4.6]]
    rooms:
      - name: Master
        points:
          - [3.2, 13.5]
          - [6, 13.5]
          - [6, 12]
          - [8.6, 12.0]
          - [8.6, 10.5]
          - [8.6, 8.5]
          - [8, 7.5]
          - [3.2, 7.5]
          - [3.2, 13.5]
      - name: Office
        points:
          - [6, 16.2]
          - [9.6, 16.2]
          - [9.6, 13.5]
          - [8.6, 12]
          - [6, 12]
          - [6, 14.5]
      - name: Master Bathroom
        points:
          - [0, 13.5]
          - [3.2, 13.5]
          - [3.2, 7.5]
          - [0, 7.5]
          - [0, 13.5]
      - name: Master Closet
        points:
          - [0, 16.5]
          - [1.5, 16.5]
          - [1.5, 17.0]
          - [6, 17.0]
          - [6, 13.5]
          - [0, 13.5]
          - [0, 16.5]
  - id: outside
    name: Outside
    bounds: [[-10, -10, -10], [28, 30, 20]]

# Locations of espresense nodes in meters
nodes:
  - name: Master
    point: [9.4, 13.7, 3.6]
    floors: ["second"]
  - name: Bathroom
    point: [0.1, 10, 3.9]
    floors: ["second", "outside"]
  - name: Upstairs Hallway
    point: [12, 10, 3.2]
    floors: ["second"]
  - name: Garage
    point: [0.75, 16.8, 0.5]
    floors: ["first", "second", "outside"]
  - name: Office
    point: [6.75, 15, 3.6]
    floors: ["second"]
  - name: Family
    point: [0.25, 0.4, 0.3]
    floors: ["first", "outside"]
  - name: Kitchen
    point: [9, 9, 0.85]
    floors: ["first"]
  - name: Dining
    point: [16.25, 3, 1.29]
    floors: ["first", "outside"]
  - name: Basement
    point: [16, 13, -1]
    floors: ["first", "second", "outside"]
  - name: Laundry
    point: [4.6, 7.5, 1]
    floors: ["first"]
  - name: Mini
    stationary: false
    point: [-2, 15, 0.5]
    floors: ["outside"]

# Devices to track
devices:
  - name: "*" # Track all named devices
  - id: "tile:*" # Track all tiles
  - id: "irk:*" # Track all IRKs
  - id: "watch:*"
  - id: "phone:*"
  - id: "wallet:*"
  - id: "keys:*"
  - id: "therm:*"
  - id: "iBeacon:*"
