- platform: group
  name: Hanging Light
  entities:
      - light.hanging_light_1
      - light.hanging_light_2
      - light.hanging_light_3

- platform: group
  name: Kitchen Island Lights
  entities:
      - light.lifx_d0_73_d5_67_6b_6a
      - light.kitchen_2
      
- platform: group
  name: Cabinet Lights
  entities:
      - light.cabinet_lights_butler_s_pantry
      - light.cabinet_lights_kitchen