# Living Room
- platform: switch
  name: Butterfly Light
  entity_id: switch.gxd_america_double_socket_2_switch_1

- platform: switch
  name: Christmas Tree Light
  entity_id: switch.gxd_america_double_socket_switch_1

- platform: switch
  name: Living Room Ceiling Fan Light
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch_3

- platform: switch
  name: Stairwell Light
  entity_id: switch.in_wall_smart_switch_120_277vac

- platform: switch
  name: Stairwell Christmas Lights
  entity_id: switch.stairwell_christmas_lights_switch_on_off

# Kitchen

- platform: switch
  name: Kitchen Tract Lights
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch

- platform: switch
  name: Butler's Pantry Light
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch_5

- platform: switch
  name: "Cabinet Lights - Kitchen"
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch_4

- platform: switch
  name: "Cabinet Lights - Butler's Pantry"
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch_2

# Dining Room

- platform: switch
  name: Entry Way Light
  entity_id: switch.ge_enbrighten_z_wave_plus_smart_switch_6

# Master Bedroom

- platform: switch
  name: Tiffany Light
  entity_id: switch.master_bedroom_tiffany_light_switch_on_off
