- platform: template
  lights:
      office_monitor_light:
          unique_id: office_monitor_light
          friendly_name: "Office Monitor Light"
          value_template:
              "{{ (states('input_text.office_monitor_light_state') | from_json).state ==
              'on' }}"
          level_template: >
              {{
                ((states('input_text.office_monitor_light_state') |
              from_json).brightness | float) 
                * 255.0
              }}
          turn_on:
              - service: rest_command.remote_light_command
                data_template:
                    service: "turn_on"
                    controller_id: "remote.office_rm4_mini"
                    device: "Office Monitor Light"
                    entity_id: "light.office_monitor_light"
                    state: "on"
                    brightness_pct: "1"
          turn_off:
              - service: rest_command.remote_light_command
                data_template:
                    service: "turn_off"
                    controller_id: "remote.office_rm4_mini"
                    device: "Office Monitor Light"
                    entity_id: "light.office_monitor_light"
                    state: "off"
                    brightness_pct: "0"
          set_level:
              - service: rest_command.remote_light_command
                data_template:
                    service: "turn_on"
                    controller_id: "remote.office_rm4_mini"
                    device: "Office Monitor Light"
                    entity_id: "light.office_monitor_light"
                    state: "on"
                    brightness_pct: "{{ (brightness | int) / 255.0 }}"
