- alias: 'Rule 1 Light on in the evening'
    trigger:
      # Prefix the first line of each trigger configuration
      # with a '-' to enter multiple
      - platform: sun
        event: sunset
        offset: '-01:00:00'
      - platform: state
        entity_id: all
        to: 'home'
    condition:
      # Prefix the first line of each condition configuration
      # with a '-'' to enter multiple
      - condition: state
        entity_id: all
        state: 'home'
      - condition: time
        after: '16:00:00'
        before: '23:00:00'
    action:
      # With a single service call, we don't need a '-' before service - though you can if you want to
      - service: homeassistant.turn_on
      entity_id: group.living_room
